config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    Job.create(job_params)
    redirect_to jobs_path
  end

  def edit
  end

  def update
    @job.update_attributes(job_params)
    redirect_to jobs_path
  end

  def destroy
    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <a class="waves-effect waves-light btn"><%= f.submit %></a>
  </div>
<%end%>

app/views/jobs/edit.html.erb
<h1>Edit Here</h1>
<%= render "form" %>

app/views/jobs/index.html.erb
<h1>Hello World</h1>

<%= link_to 'new job', new_job_path %>

<% @jobs.each do |job| %>
  <h3><%= job.title %></h3>
  <p><%= job.description %></p>
  <h5><%= link_to "Edit Posting", edit_job_path(job)%></h5>
  <h5><%= link_to "Delete Posting", job, method: :delete %></h5>
<%end%>

app/views/jobs/new.html.erb
<h2>Add a job</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="clearfix">
      <div class="left-nav">
        <ul>
          <li><%= link_to "Home", jobs_path%></li>
        </ul>
      </div>
      <div class="right-nav">
        <ul>
          <li><%=link_to "Add Job", new_job_path%></li>
        </ul>
      </div>
    </header>
    <div class="content">
      <%= yield %>
    </div>    
  </body>
</html>